import { Car } from './shared/models/carModel';
import { Tag } from './shared/models/tagModel';

export const sample_cars: Car[] = [
  {
    id: '1',
    brand: 'BMW M3',
    price: 54000,
    productionYear: 1997,
    fuelType: ['Petrol'],
    tags: ['Manual', 'Fast'],
    favourite: false,
    imageUrl: 'assets/bmw.jpg',
  },
  {
    id: '2',
    brand: 'Mercedes AMG',
    price: 78000,
    productionYear: 2017,
    fuelType: ['Petrol'],
    tags: ['Automatic', 'Fast', 'Modern'],
    favourite: true,
    imageUrl: 'assets/mercedes.jpg',
  },
  {
    id: '3',
    brand: 'Ford Focus',
    price: 5000,
    productionYear: 2004,
    fuelType: ['Diesel'],
    tags: ['Manual', 'Slow'],
    favourite: false,
    imageUrl: 'assets/ford.jpg',
  },
  {
    id: '1',
    brand: 'BMW M3',
    price: 54000,
    productionYear: 1997,
    fuelType: ['Petrol'],
    tags: ['Manual', 'Fast'],
    favourite: false,
    imageUrl: 'assets/bmw.jpg',
  },
  {
    id: '2',
    brand: 'Mercedes AMG',
    price: 78000,
    productionYear: 2017,
    fuelType: ['Petrol'],
    tags: ['Automatic', 'Fast', 'Modern'],
    favourite: true,
    imageUrl: 'assets/mercedes.jpg',
  },
  {
    id: '3',
    brand: 'Ford Focus',
    price: 5000,
    productionYear: 2004,
    fuelType: ['Diesel'],
    tags: ['Manual', 'Slow'],
    favourite: false,
    imageUrl: 'assets/ford.jpg',
  },
  {
    id: '1',
    brand: 'BMW M3',
    price: 54000,
    productionYear: 1997,
    fuelType: ['Petrol'],
    tags: ['Manual', 'Fast'],
    favourite: false,
    imageUrl: 'assets/bmw.jpg',
  },
  {
    id: '2',
    brand: 'Mercedes AMG',
    price: 78000,
    productionYear: 2017,
    fuelType: ['Petrol'],
    tags: ['Automatic', 'Fast', 'Modern'],
    favourite: true,
    imageUrl: 'assets/mercedes.jpg',
  },
  {
    id: '3',
    brand: 'Ford Focus',
    price: 5000,
    productionYear: 2004,
    fuelType: ['Diesel'],
    tags: ['Manual', 'Slow'],
    favourite: false,
    imageUrl: 'assets/ford.jpg',
  },
  {
    id: '1',
    brand: 'BMW M3',
    price: 54000,
    productionYear: 1997,
    fuelType: ['Petrol'],
    tags: ['Manual', 'Fast'],
    favourite: false,
    imageUrl: 'assets/bmw.jpg',
  },
  {
    id: '2',
    brand: 'Mercedes AMG',
    price: 78000,
    productionYear: 2017,
    fuelType: ['Petrol'],
    tags: ['Automatic', 'Fast', 'Modern'],
    favourite: true,
    imageUrl: 'assets/mercedes.jpg',
  },
  {
    id: '3',
    brand: 'Ford Focus',
    price: 5000,
    productionYear: 2004,
    fuelType: ['Diesel'],
    tags: ['Manual', 'Slow'],
    favourite: false,
    imageUrl: 'assets/ford.jpg',
  },
  {
    id: '1',
    brand: 'BMW M3',
    price: 54000,
    productionYear: 1997,
    fuelType: ['Petrol'],
    tags: ['Manual', 'Fast'],
    favourite: false,
    imageUrl: 'assets/bmw.jpg',
  },
  {
    id: '2',
    brand: 'Mercedes AMG',
    price: 78000,
    productionYear: 2017,
    fuelType: ['Petrol'],
    tags: ['Automatic', 'Fast', 'Modern'],
    favourite: true,
    imageUrl: 'assets/mercedes.jpg',
  },
];

export const sample_tags: Tag[] = [
  { name: 'All', count: 14 },
  { name: 'Fast', count: 4 },
  { name: 'Modern', count: 2 },
  { name: 'Slow', count: 3 },
];
