export const sample_cars: any[] = [
  {
    id: '1',
    brand: 'BMW M3',
    price: 54000,
    productionYear: 1997,
    fuelType: ['Petrol'],
    tags: ['Manual', 'Fast'],
    favourite: false,
    imageUrl: 'assets/bmw.jpg',
  },
  {
    id: '2',
    brand: 'Mercedes AMG',
    price: 78000,
    productionYear: 2017,
    fuelType: ['Petrol'],
    tags: ['Automatic', 'Fast', 'Modern'],
    favourite: true,
    imageUrl: 'assets/mercedes.jpg',
  },
  {
    id: '3',
    brand: 'Ford Focus',
    price: 5000,
    productionYear: 2004,
    fuelType: ['Diesel'],
    tags: ['Manual', 'Slow'],
    favourite: false,
    imageUrl: 'assets/ford.jpg',
  },
  {
    id: '1',
    brand: 'BMW M3',
    price: 54000,
    productionYear: 1997,
    fuelType: ['Petrol'],
    tags: ['Manual', 'Fast'],
    favourite: false,
    imageUrl: 'assets/bmw.jpg',
  },
  {
    id: '2',
    brand: 'Mercedes AMG',
    price: 78000,
    productionYear: 2017,
    fuelType: ['Petrol'],
    tags: ['Automatic', 'Fast', 'Modern'],
    favourite: true,
    imageUrl: 'assets/mercedes.jpg',
  },
  {
    id: '3',
    brand: 'Ford Focus',
    price: 5000,
    productionYear: 2004,
    fuelType: ['Diesel'],
    tags: ['Manual', 'Slow'],
    favourite: false,
    imageUrl: 'assets/ford.jpg',
  },
  {
    id: '1',
    brand: 'BMW M3',
    price: 54000,
    productionYear: 1997,
    fuelType: ['Petrol'],
    tags: ['Manual', 'Fast'],
    favourite: false,
    imageUrl: 'assets/bmw.jpg',
  },
  {
    id: '2',
    brand: 'Mercedes AMG',
    price: 78000,
    productionYear: 2017,
    fuelType: ['Petrol'],
    tags: ['Automatic', 'Fast', 'Modern'],
    favourite: true,
    imageUrl: 'assets/mercedes.jpg',
  },
  {
    id: '3',
    brand: 'Ford Focus',
    price: 5000,
    productionYear: 2004,
    fuelType: ['Diesel'],
    tags: ['Manual', 'Slow'],
    favourite: false,
    imageUrl: 'assets/ford.jpg',
  },
  {
    id: '1',
    brand: 'BMW M3',
    price: 54000,
    productionYear: 1997,
    fuelType: ['Petrol'],
    tags: ['Manual', 'Fast'],
    favourite: false,
    imageUrl: 'assets/bmw.jpg',
  },
  {
    id: '2',
    brand: 'Mercedes AMG',
    price: 78000,
    productionYear: 2017,
    fuelType: ['Petrol'],
    tags: ['Automatic', 'Fast', 'Modern'],
    favourite: true,
    imageUrl: 'assets/mercedes.jpg',
  },
  {
    id: '3',
    brand: 'Ford Focus',
    price: 5000,
    productionYear: 2004,
    fuelType: ['Diesel'],
    tags: ['Manual', 'Slow'],
    favourite: false,
    imageUrl: 'assets/ford.jpg',
  },
  {
    id: '1',
    brand: 'BMW M3',
    price: 54000,
    productionYear: 1997,
    fuelType: ['Petrol'],
    tags: ['Manual', 'Fast'],
    favourite: false,
    imageUrl: 'assets/bmw.jpg',
  },
  {
    id: '2',
    brand: 'Mercedes AMG',
    price: 78000,
    productionYear: 2017,
    fuelType: ['Petrol'],
    tags: ['Automatic', 'Fast', 'Modern'],
    favourite: true,
    imageUrl: 'assets/mercedes.jpg',
  },
];

export const sample_tags: any[] = [
  { name: 'All', count: 14 },
  { name: 'Fast', count: 4 },
  { name: 'Modern', count: 2 },
  { name: 'Slow', count: 3 },
];

export const sample_users: any[] = [
  {
    name: 'Ivan Georgiev',
    email: 'ivan@abv.bg',
    password: '123ivan',
    address: 'Sofia',
    isAdmin: true,
  },
  {
    name: 'Stefan Ivanov',
    email: 'stefan@abv.bg',
    password: '123stefan',
    address: 'Plovdiv',
    isAdmin: false,
  },
];
